### ISSUE TITLE
Don't initialize "new Random" within a loop

### ISSUE THREAD

**Issue by incredibleLeitman** [CapioIM/NumberGuessing#6]
https://github.com/CapioIM/NumberGuessing/blob/f71a869d1a2492d6b1f4cc2ea87e520165c5ef44/NumberGuessing/Program.cs#L20
This needs only be created once, so you could either move this up to your Main function before your loop,
or even outside of the function at all.

The same applies for constants: Usually they are placed inside the class and outside of functions
https://github.com/CapioIM/NumberGuessing/blob/f71a869d1a2492d6b1f4cc2ea87e520165c5ef44/NumberGuessing/Program.cs#L23-L24
![image](https://github.com/CapioIM/NumberGuessing/assets/24638443/7065c449-2bc5-41e0-81f2-2c16780ec4bb)

**Comment by mayisa87** [comment]
https://github.com/CapioIM/NumberGuessing/blob/2e6b518ef466d5d7c9ac3f8687aaee4f2262db46/NumberGuessing/Program.cs#L9-L15

If you want to store your constants in a separated class, you should always go for a separated class file and put it in there. Or you just move it outside your methods, so outside the static void Main() method in your case like Michael shows in his screenshot:

![image](https://github.com/CapioIM/NumberGuessing/assets/130921606/447ef269-417e-46fe-8fd0-e467948645f6)


But avoid having classes inside your classes. This will get very complicated if you are going to have larger projects including a lot of classes. Because it is very hard to find those inner classes.
